name: Build

on:
  push:
    branches: ["master"]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build on ${{ matrix.os }} with profile ${{ matrix.profile }}.
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        profile: ["dev", "release"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Restore Cache
        uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            node_modules/

          key: ${{ matrix.os }}-${{ matrix.profile }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ matrix.os }}-${{ matrix.profile }}-

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v2
        with:
          toolchain: nightly
          cache: false # We handle cache on our own.

      - name: Install Dependencies # Runs only if the runner OS is ubuntu-latest.
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get install g++ mold clang git pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0 libwayland-dev libxkbcommon-dev mesa-vulkan-drivers

      - name: Build
        run: cargo build --profile ${{ matrix.profile }} --verbose
