name: Publish To Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Restore Cache
        uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            node_modules/

          key: WebBuild-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: WebBuild-

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v2
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown
          cache: false # We handle cache on our own.

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          package-manager-cache: false # Again, we handle cache on our own.

      - name: Install Dependencies
        run: sudo apt-get install g++ mold clang git pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0 libwayland-dev libxkbcommon-dev mesa-vulkan-drivers

      - name: Install wasm-bindgen-cli
        run: cargo install wasm-bindgen-cli

      - name: Build
        run: cargo build --profile wasm-release --target wasm32-unknown-unknown --verbose

      - name: Create dist/ directory and copy over required files.
        run: mkdir dist/ && mkdir dist/assets/ && cp -r web/. dist && cp -r assets/. dist/assets

      - name: Generate Webassembly files.
        run: wasm-bindgen --out-dir dist/ --out-name Comfort3D --target web target/wasm32-unknown-unknown/wasm-release/comfort3d.wasm

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Upload Web Directory
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
